### ISSUE TITLE
(function (exports, require, module, __filename, __dirname) { const { log } = require("abr-log")("rpgen");

### ISSUE THREAD

**Issue by fat84** [dest4/radio-playlist-generator#2]
root@vps629614:~/radio-playlist-generator# node index.js
/root/radio-playlist-generator/index.js:1
(function (exports, require, module, __filename, __dirname) { const { log } = require("abr-log")("rpgen");
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by fat84** [comment]
i reinstall  update upgrade  
help me. thanks

**Comment by dest4** [comment]
Do you still have a problem? Could you clarify your request please?
